### ISSUE TITLE
Tourism Landing Page

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/LANDING-PAGES#1]
<img src=""https://www.c21stores.com/media/W1siZiIsIjIwMTYvMDUvMjYvMTEvMTQvNTIvNTE0LzAwXzA1V0VFSzNfTFBfVE9VUklTTV9WSVNJVE9SLmpwZyJdXQ/00_05WEEK3_LP_TOURISM_VISITOR.jpg?sha=38a9da3cd3768716/>

**Comment by juanmriosv** [comment]
<img =src"https://www.c21stores.com/media/W1siZiIsIjIwMTYvMDUvMjYvMTEvMTQvNTIvNTE0LzAwXzA1V0VFSzNfTFBfVE9VUklTTV9WSVNJVE9SLmpwZyJdXQ/00_05WEEK3_LP_TOURISM_VISITOR.jpg?sha=38a9da3cd3768716"/>

**Comment by juanmriosv** [comment]
smb://nj-ecomstore1/ecom_images/NEW-STRUCTURE/yFINISHED-ASSETS/05Week3-16/WEBSITE/LANDING-PAGES/TOURIST
![tourism](https://cloud.githubusercontent.com/assets/16789090/15579672/ada2cea2-2333-11e6-9c53-9db756279e1e.jpg)

**Comment by juanmriosv** [comment]
@c21hornak this has been sent to Elisabeth. It is being QA

**Comment by c21hornak** [comment]
This is live. Closing.
