### ISSUE TITLE
NEW LANDING PAGES

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/LANDING-PAGES#2]
EPIC for:
https://github.com/Century21Stores/LANDING-PAGES/issues/1 — Tourism Landing Page
https://github.com/Century21Stores/LANDING-PAGES/issues/3 — Suppressed Brand Zero Search Results Landing Page
https://github.com/Century21Stores/LANDING-PAGES/issues/4 — Suppressed Brand Zero Search Results Redirects
https://github.com/Century21Stores/LANDING-PAGES/issues/16 — New Home Page #8 floating Background

**Comment by AdenaG** [comment]
There's no description - what page is this? I think it would help to have go live date/week on here..what you think?

**Comment by juanmriosv** [comment]
There is. You are probably not looking on the board. I will show you how it works later

**Comment by AdenaG** [comment]
Yea if we can do a little run through to make sure Im using correctly, that would be great. Thanks!

**Comment by c21hornak** [comment]
Adena, this ticket, LANDING-PAGES-2, is an Epic which just contains these 2 tickets:
• Tourism Landing Page (LANDING-PAGES-1) — completed/closed
• Zero Search Results Landing Page (LANDING-PAGES-3) — this one needs QA

It's not possible to see that without using Chrome with the ZenHub Extension.
