### ISSUE TITLE
Update About Us Content Page to a Graphical Landing Page

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/LANDING-PAGES#29]
Coming soon. The [Creative Brief](https://c21.attask-ondemand.com/issue/view?ID=58c024a20059886725ef44badd1352ca) was submitted by Andrea on 3/8, and there's a [Workfront request](https://c21.attask-ondemand.com/project/view?ID=58c2d70c006cbecdded91f2776bb5920) open since 3/10 for Creative to deliver the assets.

https://www.c21stores.com/pages/about-us

**Comment by juanmriosv** [comment]
ProofHQ Image
![00_03week04_lp_aboutus](https://cloud.githubusercontent.com/assets/16789090/23959496/c2fd0158-097b-11e7-8ab1-6f603fb75080.jpg)

**Comment by juanmriosv** [comment]
@c21hornak, I have asked via [Workfront](https://c21.attask-ondemand.com/project/view?ID=58c2d70c006cbecdded91f2776bb5920&commentID=58c96ab300e6f99d9d56bee68a907986&activeTab=tab-project-updates) if any of the assets (6 heros in total) will be clickable.

**Comment by c21hornak** [comment]
@juanmriosv thanks. Did they say when this is due to be live?

**Comment by juanmriosv** [comment]
@c21hornak answer from Sonia in workfront:

> "Whenever you're able to build once we delivery. No set date, but it's a request coming from Larry so asap"

They have not delivered it yet. I've asked when are they going to deliver the assets and what is the plan for mobile (this is tricky one).

**Comment by juanmriosv** [comment]
Staging: https://www.staging.c21.weblinc.com/pages/about-us

**Comment by juanmriosv** [comment]
@c21hornak Approved by Sonia in workfront, Should I push to Prod?

**Comment by c21hornak** [comment]
@AdenaG please QA on STAGING (cross-browser): https://www.staging.c21.weblinc.com/pages/about-us

**Comment by AdenaG** [comment]
@juanmriosv 
There is a large gap between the content and the footer on mobile - STAGING & PROD.
![screen shot 2017-04-26 at 11 00 38 am](https://cloud.githubusercontent.com/assets/20344050/25441364/0407756a-2a70-11e7-91ad-7e93195ad9e9.png)

**Comment by juanmriosv** [comment]
non-issue in our end.
Unfortunately, that is the design that was sent.

**Comment by c21hornak** [comment]
Closing.
