### ISSUE TITLE
Spring Weekend Landing Page

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/LANDING-PAGES#33]
Request:
[https://c21.attask-ondemand.com/issue/view?ID=58e2c2b90071d35c80079c2d467e2b69](https://c21.attask-ondemand.com/issue/view?ID=58e2c2b90071d35c80079c2d467e2b69)

**Comment by juanmriosv** [comment]
Sent for Review to Ken Mitchell 
Ready for QA

[https://www.staging.c21.weblinc.com/pages/springpromo17](https://www.staging.c21.weblinc.com/pages/springpromo17)

**Comment by c21hornak** [comment]
Sorry - missed this.
@AdenaG ready to QA on STAGING.
@juanmriosv when does this need to go live?
