### ISSUE TITLE
Suppressed Brand Forced Redirects to Zero Search Results LP

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/LANDING-PAGES#4]
Write custom code that listens to what's submitted in the On-Site Search Field. Listen for when one of the suppressed brands is submitted, and an exact match is also found to be listed on a maintainable Google Doc, which is referenceable by this custom code, then force a redirect to a custom landing page (to be built on https://github.com/Century21Stores/LANDING-PAGES/issues/3).

**Comment by c21hornak** [comment]
What is the difference LANDING-PAGES-3 and LANDING-PAGES-4?

Is LANDING-PAGES-3 just the landing page and LANDING-PAGES-4 is the custom code that enables the redirects to the landing page?

**Comment by juanmriosv** [comment]
@c21hornak  Yes, #3 was opened just to create the Landing Page, #4 when the custom code to identify redirect was added to the requirement

**Comment by c21hornak** [comment]
This is live. Closing.
