### ISSUE TITLE
Careers Page Redesign

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/LANDING-PAGES#5]
Requested 7/25/16.
Due for 08Week1 refresh (Monday 8/1/16).

https://www.c21stores.com/pages/careers

**Comment by c21hornak** [comment]
@AdenaG ready for QA

**Comment by AdenaG** [comment]
Pass in STAGING (refresh). Creative feedback only - provided to Kate.

**Comment by c21hornak** [comment]
Page is live. Closing.
