### ISSUE TITLE
9 Square Grid Semi-Custom Home Page (HP7)

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/LANDING-PAGES#6]
Documentatin Pushed to Github

**Comment by juanmriosv** [comment]
https://github.com/Century21Stores/LANDING-PAGES/tree/master/HomePages/9_Grid

**Comment by c21hornak** [comment]
Closing.

**Comment by c21hornak** [comment]
https://www.c21stores.com/pages/hp7
