### ISSUE TITLE
Overlapping Images Semi-Custom Home Page (HP3)

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/LANDING-PAGES#7]
https://github.com/Century21Stores/LANDING-PAGES/tree/master/HomePages/Overlaping_Images

https://www.c21stores.com/pages/hp3

**Comment by juanmriosv** [comment]
@c21hornak What is what you need here?

**Comment by c21hornak** [comment]
Nothing, I was just linking the completed Github code with a ZenHub ticket.
